name: main-deploy
on:
  push:
    branches: [ main ]
    
jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: deploy to UI Server
      uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.SSH_DEPLOYMENT_HOST }}
        username: ${{ secrets.SSH_DEPLOYMENT_USERNAME }}
        key: ${{ secrets.SSH_DEPLOYMENT_SECRET }}
        port: ${{ secrets.SSH_DEPLOYMENT_PORT }}
        script: |
          cd /private
          if [ -d "lunar-calendar-spa" ]; then
          cd lunar-calendar-spa
          git checkout main
          git pull
          cd client
          # yarn install
          npm install
          # yarn build
          npm run build
          cp -r dist/. ../../../web/
          else
          git clone ${{ secrets.SSH_DEPLOYMENT_SOURCE }}
          fi
          ls -la
